version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    image: bigtruedata/php-mysqli:7-apache
    container_name: php-app
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    links:
      - "db"
  web:
    image: nginx
    container_name: nginx
    depends_on:
      - db
      - app
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    links:
      - "app"
